disallowed-methods = [
    "std::env::var",
    "std::env::var_os",
]
disallowed-types = []
cognitive-complexity-threshold = 30
single-char-binding-names-threshold = 4
too-many-arguments-threshold = 7
type-complexity-threshold = 250
enum-variant-name-threshold = 3
literal-representation-threshold = 10000